!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
MODULE MODI_GOTO_WRAPPER_TEB_PATCH
CONTAINS
! ####################################################################################
SUBROUTINE GOTO_WRAPPER_TEB_PATCH(B, DGCT, DGMT, T, TGD, TGDPE, TGR, TGRPE, KTO_PATCH)
!
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_t, DIAG_CUMUL_TEB_GOTO_PATCH
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_t, DIAG_MISC_TEB_GOTO_PATCH
USE MODD_TEB_n, ONLY : TEB_t, TEB_GOTO_PATCH
USE MODD_BEM_n, ONLY : BEM_t, BEM_GOTO_PATCH
USE MODD_TEB_GARDEN_n, ONLY : TEB_GARDEN_t, TEB_GARDEN_GOTO_PATCH
USE MODD_TEB_GARDEN_PGD_EVOL_n, ONLY : TEB_GARDEN_PGD_EVOL_t, TEB_GARDEN_PGD_EVOL_GOTO_PATCH
USE MODD_TEB_GREENROOF_n, ONLY : TEB_GREENROOF_t, TEB_GREENROOF_GOTO_PATCH
USE MODD_TEB_GREENROOF_PGD_EVOL_n, ONLY : TEB_GREENROOF_PGD_EVOL_t, TEB_GREENROOF_PGD_EVOL_GOTO_PATCH
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
!
TYPE(BEM_t), INTENT(INOUT) :: B
TYPE(DIAG_CUMUL_TEB_t), INTENT(INOUT) :: DGCT
TYPE(DIAG_MISC_TEB_t), INTENT(INOUT) :: DGMT
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_GARDEN_t), INTENT(INOUT) :: TGD
TYPE(TEB_GARDEN_PGD_EVOL_t), INTENT(INOUT) :: TGDPE
TYPE(TEB_GREENROOF_t), INTENT(INOUT) :: TGR
TYPE(TEB_GREENROOF_PGD_EVOL_t), INTENT(INOUT) :: TGRPE
INTEGER,INTENT(IN) :: KTO_PATCH
!
INTEGER            :: ICURRENT_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB_PATCH',0,ZHOOK_HANDLE)
!
 CALL DIAG_CUMUL_TEB_GOTO_PATCH(DGCT,KTO_PATCH)
 CALL DIAG_MISC_TEB_GOTO_PATCH(DGMT,KTO_PATCH)
 CALL TEB_GOTO_PATCH(T,KTO_PATCH)
 CALL BEM_GOTO_PATCH(B,KTO_PATCH)
 CALL TEB_GARDEN_PGD_EVOL_GOTO_PATCH(TGDPE,KTO_PATCH)
 CALL TEB_GREENROOF_PGD_EVOL_GOTO_PATCH(TGRPE,KTO_PATCH)
 CALL TEB_GARDEN_GOTO_PATCH(TGD,KTO_PATCH)
 CALL TEB_GREENROOF_GOTO_PATCH(TGR,KTO_PATCH)
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB_PATCH',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TEB_PATCH
END MODULE

