!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
MODULE MODD_SURFEX_n
!
USE MODD_AGRI_n, ONLY : AGRI_t
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_t
USE MODD_DATA_TEB_GARDEN_n, ONLY : DATA_TEB_GARDEN_t
USE MODD_DATA_TEB_GREENROOF_n, ONLY : DATA_TEB_GREENROOF_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_FLAKE_n, ONLY : DIAG_FLAKE_t
USE MODD_DIAG_IDEAL_n, ONLY : DIAG_IDEAL_t
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_t
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_SEAFLUX_n, ONLY : DIAG_SEAFLUX_t
USE MODD_DIAG_SEAICE_n, ONLY : DIAG_SEAICE_t
USE MODD_DIAG_SURF_ATM_n, ONLY : DIAG_SURF_ATM_t
USE MODD_DIAG_TEB_GARDEN_n, ONLY : DIAG_TEB_GARDEN_t
USE MODD_DIAG_TEB_GREENROOF_n, ONLY : DIAG_TEB_GREENROOF_t
USE MODD_DIAG_TEB_n, ONLY : DIAG_TEB_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_DIAG_WATFLUX_n, ONLY : DIAG_WATFLUX_t
USE MODD_DST_n, ONLY : DST_t
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_t
USE MODD_EMIS_GR_FIELD_n, ONLY : EMIS_GR_FIELD_t
USE MODD_FLAKE_GRID_n, ONLY : FLAKE_GRID_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_FLAKE_SBL_n, ONLY : FLAKE_SBL_t
USE MODD_GR_BIOG_GARDEN_n, ONLY : GR_BIOG_GARDEN_t
USE MODD_GR_BIOG_GREENROOF_n, ONLY : GR_BIOG_GREENROOF_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_IDEAL_n, ONLY : IDEAL_t
USE MODD_ISBA_CANOPY_n, ONLY : ISBA_CANOPY_t
USE MODD_ISBA_GRID_n, ONLY : ISBA_GRID_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_t
USE MODD_PACK_CH_ISBA, ONLY : PACK_CH_ISBA_t
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_t
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
USE MODD_SEAFLUX_GRID_n, ONLY : SEAFLUX_GRID_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SEAFLUX_SBL_n, ONLY : SEAFLUX_SBL_t
USE MODD_SLT_n, ONLY : SLT_t
USE MODD_SSO_CANOPY_n, ONLY : SSO_CANOPY_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURF_ATM_SSO_n, ONLY : SURF_ATM_SSO_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_TEB_CANOPY_n, ONLY : TEB_CANOPY_t
USE MODD_TEB_GARDEN_OPTION_n, ONLY : TEB_GARDEN_OPTIONS_t
USE MODD_TEB_GARDEN_PGD_n, ONLY : TEB_GARDEN_PGD_t
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TEB_GREENROOF_OPTIONS_t
USE MODD_TEB_GREENROOF_PGD_n, ONLY : TEB_GREENROOF_PGD_t
USE MODD_TEB_GRID_n, ONLY : TEB_GRID_t
USE MODD_TEB_IRRIG_n, ONLY : TEB_IRRIG_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_t
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_OPTIONS_t
USE MODD_WATFLUX_GRID_n, ONLY : WATFLUX_GRID_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
USE MODD_WATFLUX_SBL_n, ONLY : WATFLUX_SBL_t
!
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_t
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_t
USE MODD_TEB_GARDEN_n, ONLY : TEB_GARDEN_t
USE MODD_TEB_GARDEN_PGD_EVOL_n, ONLY : TEB_GARDEN_PGD_EVOL_t
USE MODD_TEB_GREENROOF_n, ONLY : TEB_GREENROOF_t
USE MODD_TEB_GREENROOF_PGD_EVOL_n, ONLY : TEB_GREENROOF_PGD_EVOL_t
USE MODD_TEB_n, ONLY : TEB_t
!
!
!---------------------------------------------------------------------------
!
TYPE FLAKE_MODEL_t
!
TYPE(CH_FLAKE_t) :: CHF
TYPE(DIAG_FLAKE_t) :: DGF
TYPE(DIAG_MISC_FLAKE_t) :: DGMF
TYPE(FLAKE_t) :: F
TYPE(FLAKE_GRID_t) :: FG
TYPE(FLAKE_SBL_t) :: FSB
!
END TYPE FLAKE_MODEL_t
!
TYPE WATFLUX_MODEL_t
!
TYPE(CH_WATFLUX_t) :: CHW
TYPE(DIAG_WATFLUX_t) :: DGW 
TYPE(WATFLUX_GRID_t) :: WG
TYPE(WATFLUX_t) :: W 
TYPE(WATFLUX_SBL_t) :: WSB
!
END TYPE WATFLUX_MODEL_t
!
TYPE SEAFLUX_MODEL_t
!
TYPE(CH_SEAFLUX_t) :: CHS
TYPE(DATA_SEAFLUX_t) :: DTS
TYPE(DIAG_SEAFLUX_t) :: DGS
TYPE(DIAG_OCEAN_t) :: DGO
TYPE(DIAG_SEAICE_t) :: DGSI 
TYPE(OCEAN_t) :: O
TYPE(OCEAN_REL_t) :: OR
TYPE(SEAFLUX_GRID_t) :: SG
TYPE(SEAFLUX_t) :: S 
TYPE(SEAFLUX_SBL_t) :: SSB
!
END TYPE SEAFLUX_MODEL_t
!
TYPE ISBA_MODEL_t
!
TYPE(AGRI_t) :: AG
TYPE(CH_ISBA_t) :: CHI
TYPE(DATA_ISBA_t) :: DTI
TYPE(DIAG_EVAP_ISBA_t) :: DGEI
TYPE(DIAG_ISBA_t) :: DGI
TYPE(DIAG_MISC_ISBA_t) :: DGMI
TYPE(GR_BIOG_t) :: GB
TYPE(ISBA_CANOPY_t) :: ICP
TYPE(ISBA_GRID_t) :: IG
TYPE(ISBA_t) :: I
TYPE(PACK_CH_ISBA_t) :: PKCI
TYPE(PACK_DIAG_ISBA_t) :: PKDI
TYPE(PACK_ISBA_t) :: PKI
!
END TYPE ISBA_MODEL_t
!
TYPE TEB_GARDEN_MODEL_t
!
TYPE(TEB_VEG_OPTIONS_t) :: TVG
TYPE(DATA_TEB_GARDEN_t) :: DTGD
TYPE(DIAG_TEB_GARDEN_t) :: DGTGD
TYPE(GR_BIOG_GARDEN_t) :: GBGD 
TYPE(TEB_GARDEN_OPTIONS_t) :: TGDO
TYPE(TEB_GARDEN_PGD_t) :: TGDP
TYPE(TEB_GARDEN_t) :: TGD 
TYPE(TEB_GARDEN_PGD_EVOL_t) :: TGDPE
TYPE(TEB_IRRIG_t) :: TIR
!
END TYPE TEB_GARDEN_MODEL_t
!
TYPE TEB_GREENROOF_MODEL_t
!
TYPE(DATA_TEB_GREENROOF_t) :: DTGR
TYPE(DIAG_TEB_GREENROOF_t) :: DGTGR
TYPE(GR_BIOG_GREENROOF_t) :: GBGR
TYPE(TEB_GREENROOF_OPTIONS_t) :: TGRO
TYPE(TEB_GREENROOF_PGD_t) :: TGRP
TYPE(TEB_GREENROOF_t) :: TGR
TYPE(TEB_GREENROOF_PGD_EVOL_t) :: TGRPE
!
END TYPE TEB_GREENROOF_MODEL_t
!
TYPE TEB_MODEL_t
!
TYPE(CH_TEB_t) :: CHT 
TYPE(DATA_TEB_t) :: DTT
TYPE(DIAG_MISC_TEB_OPTIONS_t) :: DGMTO
TYPE(DIAG_TEB_t) :: DGT 
TYPE(DIAG_UTCI_TEB_t) :: DGUT 
TYPE(TEB_CANOPY_t) :: TCP
TYPE(TEB_GRID_t) :: TG
TYPE(TEB_OPTIONS_t) :: TOP
TYPE(TEB_PANEL_t) :: TPN
TYPE(DIAG_CUMUL_TEB_t) :: DGCT
TYPE(DIAG_MISC_TEB_t) :: DGMT
TYPE(TEB_t) :: T
!
TYPE(BLD_DESC_t) :: BDD
TYPE(BEM_OPTIONS_t) :: BOP 
TYPE(DATA_BEM_t) :: DTB
TYPE(BEM_t) :: B
!
END TYPE TEB_MODEL_t
!
TYPE SURFEX_t 
!
TYPE(DATA_COVER_t) :: DTCO
TYPE(DATA_TSZ0_t) :: DTZ
TYPE(DUMMY_SURF_FIELDS_t) :: DUU
!
TYPE(SURF_ATM_GRID_t) :: UG 
TYPE(SURF_ATM_t) :: U
TYPE(DIAG_SURF_ATM_t) :: DGU 
TYPE(SURF_ATM_SSO_t) :: USS 
TYPE(SSO_CANOPY_t) :: SSCP
!
TYPE(DIAG_IDEAL_t) :: DGL
TYPE(IDEAL_t) :: L
!
TYPE(SV_t) :: SV 
TYPE(CH_SURF_t) :: CHU
TYPE(CH_EMIS_FIELD_t) :: CHE
TYPE(CH_EMIS_SNAP_t) :: CHN
TYPE(EMIS_GR_FIELD_t) :: EGF
TYPE(DST_t) :: DST 
TYPE(SLT_t) :: SLT 
!
TYPE(FLAKE_MODEL_t) :: FM
TYPE(WATFLUX_MODEL_t) :: WM
TYPE(SEAFLUX_MODEL_t) :: SM
TYPE(ISBA_MODEL_t) :: IM
TYPE(TEB_MODEL_t) :: TM
TYPE(TEB_GARDEN_MODEL_t) :: GDM
TYPE(TEB_GREENROOF_MODEL_t) :: GRM
!
END TYPE SURFEX_t
!
END MODULE MODD_SURFEX_n
